lineChart:
    pattern:  /googleChartBundle/lineChart
    defaults: { _controller: GoogleChartBundle:Showroom:lineChart }

pieChart:
    pattern:  /googleChartBundle/pieChart
    defaults: { _controller: GoogleChartBundle:Showroom:pieChart }

tutorial:
    pattern:  /googleChartBundle/tutorial
    defaults: { _controller: GoogleChartBundle:Tutorial:index }
