showroom:
    pattern:  /googleChartBundle/lineChart
    defaults: { _controller: GoogleChartBundle:Showroom:lineChart }

tutorial:
    pattern:  /googleChartBundle/tutorial
    defaults: { _controller: GoogleChartBundle:Tutorial:index }
